version: '3.9'
services:
  # PHP-FPM Service
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql-db 

  # NGINX Service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/share/nginx/html
    ports:
      - "8088:80"
    depends_on:
      - php-fpm
      - mysql-db

  # MySQL Database Service
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
      PMA_PORT: 8088
    
    depends_on:
      - mysql-db
