version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
      - pma
    networks:
      - internal
    

  php:
    build: ./images/php
    volumes:
      - ./www:/var/www/
    networks:
      - internal

  pma:
    # image: phpmyadmin:latest
    image: traefik/whoami
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      PMA_ABSOLUTE_URI: http://localhost:8000/admin/
    networks:
      - internal
    ports:
      - "3333:3306"  # порт для MySQL

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    networks:
      - internal
    depends_on:
      - pma

networks:
  internal:
    driver: bridge
    
   
