version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
      - pma
    networks:
      - internal
  php:
    build: ./images/php
    volumes:
      - ./www:/var/www/
    networks:
      - internal
  pma:
    # image: phpmyadmin:latest
    image: traefik/whoami
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
      PMA_ABSOLUTE_URI: http://localhost:8000/admin/
    networks:
      - internal
networks:
  internal:
    driver: bridge
